### ISSUE TITLE
Suggestiong on Credential Management

### ISSUE THREAD

**Issue by JonnMsft** [janegilring/Tesla#1]
Great stuff Jan! You might try using the default credential management, at least for the Scheduled Task case. Once you call Connect-Tesla without the -NoProfile parameter, the encrypted credential is stored in the user profile for the currently logged-on user. I suspect that you can skip Connect-Tesla entirely as long as the task runs under that same credential. I can't speak for Azure Automation.

**Comment by janegilring** [comment]
Ah, didn't know that...thanks!

**Comment by janegilring** [comment]
A note about the module's built-in support for persisting credentials is now added to the intro [article](http://www.powershell.no/homeautomation/2017/02/19/manage-tesla-climate-control-system-using-powershell.html)
